Milestone 3 - Game logic
guirecordon/tictactoe pull request #3
Opened 2020-05-19 18:17 UTC by guirecordon

We split our TicTacToe class which has always been in the main file into three different classes in total. We added the classes Player and Board each into their separate files called "player.rb" and "board.rb" respectively. 
All the classes were instantiated inside of each other every time their methods need to be called and the game is working exactly as it was before.

2020-05-19 19:35 UTC, Dandush03 reviewed
# Statush: :red_circle: Required Changes :red_circle: 
## Great Attemp on this one

### There are some changes you must do before submitting for another review
- [ ] PLEASE RENAME YOUR MAIN FILE TO MAIN.RB SINCE LINTER IS NOT CHECKING FOR LINTERS ERROR ON IT
 > Stickler got updated and with it, they change how files are reviews. so Rubocop on stickler will only review your file if it has it an extension. I hope you understand it's not an issue from our end but it's a most.
- [ ] Use attr_accessors only when there is no other option to it. Don't forget you can always create a function to set or get a value.
- [ ] No use of Puts/Print outside main.rb

## here below I will add some more comments

## Happy Coding :computer: & GL

##### Daniel Laloush

2020-05-19 19:35 UTC, Dandush03 commented on bin/main
> +require_relative '../lib/game_logic.rb'
please put this at the top of your document

2020-05-19 19:35 UTC, Dandush03 commented on lib/player.rb
> +  end
I'm confident you can make this long code into a simple and more elegant way with some loops

2020-05-19 19:35 UTC, Dandush03 commented on lib/player.rb
> +  attr_accessor :arr_player1, :arr_player2, :player1, :player2
Use attr_accessor only when needed as explained above

2020-05-19 19:35 UTC, Dandush03 commented on lib/board.rb
> +  attr_accessor :player, :numbers, :arr_player1, :arr_player2
Use attr_accessor only when needed as explained above

2020-05-19 19:35 UTC, Dandush03 commented on lib/player.rb
> +        puts 'Player 2 wins!'
no `puts` allowed in this file

2020-05-19 19:35 UTC, Dandush03 commented on lib/player.rb
> +      puts "It's a tie! Play again."
no `puts` allowed in this file

2020-05-19 19:35 UTC, Dandush03 commented on lib/board.rb
> +    print "\n#{@numbers[0]} | #{@numbers[1]} | #{@numbers[2]}
no `print` allowed in this file

2020-05-20 00:01 UTC, MarioDena requested changes
Hello! Good job implementing the requested changes :medal_military: , however your commit messages are lacking.

## Changes required 

- [x] Please change your commit message on commit `451ba72` right now it reads "attr_reader" This message is not descriptive or meaningful, please remember this is required on all projects. We need to be careful of following this basic rules and do not forget about them. This is because when you came back to a big project you need to have descriptive messages in case you want to rollback.

## Optional Changes

- [ ] I would update the read.me file a little bit on every milestone but of course this is a recommendation and not mandatory [OPTIONAL]

After making the requested changes please re-submit your project for re-review.

Cheers! :+1:

2020-05-20 19:34 UTC, Anna-Myzukina commented
## Hi team ! Very nice project! :wave: 

# You did a great job, approved  :+1:

* NOTE Ruby methods automatically returns the last evaluated statement therefore, there is no need for explicit declaration `return`

### Go and merge to development.
`Goodluck in your last milestone Happy coding ` <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"><img class="emoji" alt="computer" height="25" width="25" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"></g-emoji>

2020-05-20 20:05 UTC, merged